config/routes.rb
Rails.application.routes.draw do
  get 'charges/new'
  get 'charges/create'
  get 'sessions/new'
  get 'cart' => 'product#cart'
  get 'checkout' => 'product#checkout'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get 'sale' => 'search#sale'
  get 'recent' =>'search#recent'
  get 'result' =>'search#result'
  get 'about' =>'search#about'
  get 'contact' =>'search#contact'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :category, only: [:show]
  resources :user
  resources :product, only: [:index, :show]do
    member do
      post :add_item
      post :remove_item
    end
    collection do
      post :clear_cart
      post :make_order
    end
  end

  resources :charges, only: [:new, :create]

  root to: 'product#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, :security, presence: true
  validates :name, uniqueness: true
end

app/models/page.rb
class Page < ApplicationRecord
  validates :title,:description, presence: true

end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :purchase_products
  has_many :purchases, through: :purchase_products

  validates :name, :category_id, :price, :stock, presence: true
  validates :price, :stock, numericality: true

  mount_uploader :image, ImageUploader

end

app/models/province.rb
class Province < ApplicationRecord
  validates :name, presence: true
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :user
  has_many :purchase_products, :dependent => :destroy
  has_many :products, through: :purchase_products

  validates :user_id, :status, presence: true
  validates :subtotal, :total, numericality: true

  accepts_nested_attributes_for :purchase_products, allow_destroy: true
end

app/models/purchase_product.rb
class PurchaseProduct < ApplicationRecord
  belongs_to :product
  belongs_to :purchase
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :province
  validates :name, :email, :password,:address,:city,:country,:province, presence: true
  validates :email, uniqueness: true

  def get_object
    return this
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
    @amount = session[:purchase]["total"].to_d
    @description = "Purchase at YottaByte"
  end

  def create
    # Amount in cents
  @amount = (session[:purchase]["total"].to_i * 100).round()

  @customer = Stripe::Customer.create(
    :email => params[:stripeEmail],
    :source  => params[:stripeToken]
  )

  @charge = Stripe::Charge.create(
    :customer    => @customer.id,
    :amount      => @amount,
    :description => 'Rails Stripe customer',
    :currency    => 'cad'
  )

  if @charge.paid && @charge.amount == @amount
    @purchase = Purchase.find(session[:purchase]["id"])
    @purchase.status = "Paid"
    @purchase.save()
    session[:purchase] = nil
    redirect_to root_url
  end

rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to new_charge_path
end
end

app/controllers/product_controller.rb
class ProductController < ApplicationController
  require 'date'

  def index
    @product_collection = Product.order(:name).page(params[:page]).per(5)
    @product_count = @product_collection.count
  end

  def show
    @product_collection = Product.find(params[:id])
  end

  def add_item
    id = params[:id].to_i
    ids =[]
    session[:cart].each do |c|
      ids << c["id"]
    end
    unless ids.include?(id)
      session[:cart]  << {:id => id, :qty => params[:qty]}
    else
      session[:cart].each do |c|
        if c["id"] == id
           c["qty"] = params[:qty]
        end
      end
    end
    redirect_to root_url
  end

  def checkout
    if session[:user] == nil
      redirect_to '/login'
    end
    @i = 0
    @subtotal = calculate_total()
    @prov = Province.first()
  end

  def remove_item
    id = params[:id].to_i
    i = 0
    session[:cart].each do |c|
      if c["id"] == id
        break
      end
      i = i +1
    end
    puts i
    session[:cart].delete_at(i)
    redirect_to root_url
  end

  def cart
    @i = 0
  end

  def make_order
    i = 0

    @prov = Province.find(session[:user]["province_id"])
    @purchase = Purchase.new(:user => @user,
                             :user_id => @user.id,
                             :status => "Purchased",
                             :subtotal => calculate_total().round(2),
                             :total=> (calculate_total() + (calculate_total() * @prov.GST) + (calculate_total() * @prov.HST) + (calculate_total() * @prov.PST)).round(2))
    session[:purchase] = @purchase
    @cart.each do |c|
      PurchaseProduct.new(:product => c,
                           :product_id => c.id,
                           :purchase => @purchase,
                           :purchase_id => @purchase.id,
                           :quantity => session[:cart][i]["qty"],
                           :price => c.price,
                           :total => c.price * 1).save
          i = i +1
    end
    redirect_to charges_new_path
  end

  def calculate_total
    sum = 0
    i = 0
    @cart.each do |c|
      sum = sum + c.price * session[:cart][i]["qty"].to_i
      i = i +1
    end
    return sum.round(2)
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def sale
    @product_collection = Product.where("onsale <> 'false'").page(params[:page]).per(5)
  end

  def result
    if params[:categories] != nil
      @cat = params[:categories]
      @product_collection = Product.where("name LIKE '%" + params[:keyword] + "%' OR
                                          description LIKE '%" + params[:keyword] + "%' AND
                                          category_id IN (" + @cat.join(",") + ")"  ).page(params[:page]).per(5)

    else
      @product_collection = Product.where("name LIKE '%" + params[:keyword] + "%' OR
        description LIKE '%" + params[:keyword] + "%'").page(params[:page]).per(5)
    end
  end

  def recent
    @product_collection = Product.where("updated_at >= ?", Date.today()-7).page(params[:page]).per(5)
  end

  def about
    @page = Page.where("title LIKE 'About'")
  end

  def contact
    @page = Page.where("title LIKE 'Contact'")
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def new
  end

  def create
    @user = User.new(:name => params[:user][:name],
                    :email => params[:user][:email],
                    :password => params[:user][:password],
                    :address => params[:user][:address],
                    :city => params[:user][:city],
                    :country => params[:user][:country],
                    :province =>Province.find(params[:user][:province]),
                    :postalcode => params[:user][:postalcode])
    @user.save
    redirect_to root_url
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YottaBytev2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <img src="/assets/Yottabyte_Logo_Horizontal.png" alt= "Logo" height="50" width="200">
    <%= render partial: 'shared/nav'%>
    </header>

    <%= yield %>
  <!-- <footer>
      <h2 class="ui header" id="footer_title">
        <img src="/assets/Yottabyte_Logo.jpg">
        <div class="content" id="title">
          Yottabyte
          <div class="sub header" id="title">Where data is sick</div>
        </div>
      </h2>
      <nav clas="ui secondary pointing menu" id="footer_nav">
        <div class="item"><%= link_to 'Home',root_path%></div>
        <div class="item"><a href ="/about" >About</a></div>
        <div class="item"><a href="/cart">Shopping Cart</a></div>
        <div id="break"> </div>
        <div class="item"><a href="/checkout">Checkout</a></div>
        <div class="item" ><a href="/sale">On Sale</a></div>
        <div class="item" ><a href="/recent">Recently Updated</a></div>
        <div class="item"><a href ="/contact">Contact</a></div>
      </nav>
      <p>Yottabyte is not responsible for misprints or errors on product prices or information, for more information please see our Site Terms of Use. ©1996-2018 Yottabyte, Inc. All Rights Reserved. - W01</p>
    </footer>-->
  </body>
</html>

app/views/shared/_header.html.erb
<header>
    <h1>YottaByte</h1>
    <div class="ui dropdown">
    <div class="text">Categories</div>
    <i class="dropdown icon"></i>
    <div class="menu">
      <div class="header">Categories</div>
      <div class="item">Clothing</div>
      <div class="item">Home Goods</div>
      <div class="item">Bedroom</div>
      <div class="divider"></div>
      <div class="header">Order</div>
      <div class="item">Status</div>
      <div class="item">Cancellations</div>
    </div>
  </div>
</header>

app/views/shared/_nav.html.erb
<form id="searchForm" class="ui form" action="/result" method="get">
  <div class="field">
    <input type="text" id="keyword" name="keyword" placeholder="Search"/>
  </div>
  <div class="field">
    <select multiple class="label ui selection fluid dropdown" id="categories" name="categories[]">
      <%Category.order(:name).each do |category|%>
        <option value="<%=category.id%>"><%=category.name%></option>
      <%end%>
    </select>
  </div>
  <!--<input class="ui button" id="commit" name="commit" type="submit" value="Search" /> --->
</form>
<div class="ui menu" id="menu">
        <div class= "menu">
          <div class="item"><%= link_to 'Home',root_path%></div>
          <div class="item"><a href ="/about">About</a></div>
          <div class="ui simple dropdown item">
            <div class="text">Hardware</div>
              <i class="dropdown icon"></i>
                <div class="menu">
                 <div class="header">Categories</div>
                 <%Category.order(:name).each do |category| %>
                  <div class="item"><%=link_to category.name, category%></div>
                 <%end%>
                </div>
          </div>
      <div class="ui simple dropdown item">
        <div class="text">Orders</div>
         <i class="dropdown icon"></i>
          <div class="menu">
            <div class="item"><a href="/cart">Shopping Cart</a></div>
            <div class="item"><a href="/checkout">Checkout</a></div>
          </div>
        </div>
      </div>
        <div class="item" ><a href="/sale">On Sale</a></div>
        <div class="item" ><a href="/recent">Recently Updated</a> </div>
        <div class="item"><a href ="/contact">Contact</a></div>
        <div class ="item">
          <%= link_to 'Clear Cart', clear_cart_product_index_path, method: :post%>
        </div>
        <div id="login" class="item">
          <%if session[:user] != nil%>
            Hello, <%=session[:user]["name"]%> <%= link_to "Log out", logout_path, method: :delete %>
          <%else %>
            <a href="/login">Login</a> / <a href="/user/new">Register</a>
          <%end%>
        </div>
      </div>

