config/routes.rb
Rails.application.routes.draw do
  get 'charges/new'
  get 'charges/create'
  get 'sessions/new'
  get 'cart' => 'product#cart'
  get 'checkout' => 'product#checkout'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get 'sale' => 'search#sale'
  get 'recent' =>'search#recent'
  get 'result' =>'search#result'
  get 'about' =>'search#about'
  get 'contact' =>'search#contact'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :category, only: [:show]
  resources :user
  resources :product, only: [:index, :show]do
    member do
      post :add_item
      post :remove_item
    end
    collection do
      post :clear_cart
      post :make_order
    end
  end

  resources :charges, only: [:new, :create]

  root to: 'product#index'
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :purchase_products
  has_many :purchases, through: :purchase_products

  validates :name, :category_id, :price, :stock, presence: true
  validates :price, :stock, numericality: true

  mount_uploader :image, ImageUploader

end

app/controllers/product_controller.rb
class ProductController < ApplicationController
  require 'date'

  def index
    @product_collection = Product.order(:name).page(params[:page]).per(5)
    @product_count = @product_collection.count
  end

  def show
    @product_collection = Product.find(params[:id])
  end

  def add_item
    id = params[:id].to_i
    ids =[]
    session[:cart].each do |c|
      ids << c["id"]
    end
    unless ids.include?(id)
      session[:cart]  << {:id => id, :qty => params[:qty]}
    else
      session[:cart].each do |c|
        if c["id"] == id
           c["qty"] = params[:qty]
        end
      end
    end
    redirect_to root_url
  end

  def checkout
    if session[:user] == nil
      redirect_to '/login'
    end
    @i = 0
    @subtotal = calculate_total()
    @prov = Province.first()
  end

  def remove_item
    id = params[:id].to_i
    i = 0
    session[:cart].each do |c|
      if c["id"] == id
        break
      end
      i = i +1
    end
    puts i
    session[:cart].delete_at(i)
    redirect_to root_url
  end

  def cart
    @i = 0
  end

  def make_order
    i = 0

    @prov = Province.find(session[:user]["province_id"])
    @purchase = Purchase.new(:user => @user,
                             :user_id => @user.id,
                             :status => "Purchased",
                             :subtotal => calculate_total().round(2),
                             :total=> (calculate_total() + (calculate_total() * @prov.GST) + (calculate_total() * @prov.HST) + (calculate_total() * @prov.PST)).round(2))
    session[:purchase] = @purchase
    @cart.each do |c|
      PurchaseProduct.new(:product => c,
                           :product_id => c.id,
                           :purchase => @purchase,
                           :purchase_id => @purchase.id,
                           :quantity => session[:cart][i]["qty"],
                           :price => c.price,
                           :total => c.price * 1).save
          i = i +1
    end
    redirect_to charges_new_path
  end

  def calculate_total
    sum = 0
    i = 0
    @cart.each do |c|
      sum = sum + c.price * session[:cart][i]["qty"].to_i
      i = i +1
    end
    return sum.round(2)
  end

end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/product/_product.html.erb
<%if show_link%>
  <div class="four wide column">
<%else%>
  <div class="four wide column">
<%end%>
<% if product.image.present?%>
  <% if show_link%>
    <%= image_tag product.image.url(:medium), alt: "Product", :class => "product_image"%>
  <%else%>
    <%= image_tag product.image.url ,alt: "Product"%>
  <%end%>
<%end%>
<%if show_link %>
  <div>
    <b>Name: </b><%= link_to product.name, product,:class =>"product_link"%>
  </div>
<%else%>
  <div id="singleItem">
    <b><%= product.name%></b>
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <%= form_for(:session, url: add_item_product_path(product)) do |f| %>
          <input id="qty" type="number" name="qty" min="1" max="99" value="1" step="1">
          <%= f.submit "Add Item", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
<%end%>
<%if cart%>
  <p>Qty: <%=session[:cart][@i]["qty"]%></p>
  <% @i = @i +1%>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
          <%= form_for(:session, url: add_item_product_path(product)) do |f| %>
              <input id="qty" type="number" name="qty" min="1" max="99" value="1" step="1">
              <%= f.submit "Update Item", class: "btn btn-primary" %>
          <% end %>
    </div>
  </div>
  <%= link_to 'Remove From Cart', remove_item_product_path(product),:class =>"product_link", method: :post%>
<%end%>
  <b>Price: $</b><%= product.price%>
  <% if !cart%>
    <b>Stock: </b><%= product.stock%>
  <%end%>
  <br />
  <%if !show_link %>
    <b>SKU:</b><%= product.sku%> <br />
    <b>Description: </b><%= product.description%>
  <%end%>
</div>



app/views/product/cart.html.erb
<h1>Shopping Cart</h1>
<div class ="ui grid" id="grid">
  <%= render partial: 'product', collection: @cart,
          locals: {show_link: true,cart: true,checkout:false}%>
</div>

app/views/product/checkout.html.erb
<h1>Checkout</h1>
<h4>Subtotal: $<%=@subtotal%></h4>
<h2>Taxes:</h2>
<h4>GST: $<%=(@subtotal*@prov.GST).round(2) %></h4>
<h4>PST: $<%=(@subtotal*@prov.PST).round(2) %></h4>
<h4>HST: $<%=(@subtotal*@prov.HST).round(2) %></h4>
<h3>Total: $<%=(@subtotal +(@subtotal*@prov.GST)).round(2) %></h3>
<p><%= link_to 'Make Purchase', make_order_product_index_path, method: :post%></p>
<div class ="ui grid">
  <%= render partial: 'product', collection: @cart,
          locals: {show_link: true,cart: true,checkout:true}%>
</div>

app/views/product/index.html.erb
<div class ="ui grid" id="grid">
  <%= render partial: 'product', collection: @product_collection,
          locals: {show_link: true,cart: false,checkout:false}%>
<%= paginate @product_collection %>
</div>

app/views/product/show.html.erb
<%= render partial: 'product', object: @product_collection,
          locals: {show_link: false,cart: false,checkout:false}%>
<%= link_to 'All Products',root_path%>